/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setConfig(config: LoggerConfig): EnvConfig | null
export declare function trace(message: any): void
export declare function info(message: any): void
export declare function debug(message: any): void
export declare function warn(message: any): void
export declare function error(message: any): void
export declare function fatal(message: any): void
export declare function shutdown(): void
export const enum LogLevel {
  Trace = 0,
  Debug = 1,
  Info = 2,
  Warn = 3,
  Error = 4,
  Fatal = 5
}
export const enum OutputTarget {
  Stdout = 0,
  Stderr = 1,
  File = 2,
  Null = 3
}
export const enum OutputFormat {
  Text = 0,
  Json = 1
}
export interface LogEntry {
  level: LogLevel
  msg: any
  time: number
  pid: number
}
export interface MaskingConfig {
  keyword?: string
  exact?: Array<string>
  partial?: Array<string>
  regex?: Array<string>
}
export interface OutputConfig {
  color?: boolean
  format: OutputFormat
  target: OutputTarget
  filePath?: string
  maxFileSize?: number
  maxBackups?: number
  rotateDaily?: boolean
  batchEnabled?: boolean
  batchSize?: number
  batchIntervalMs?: number
  masking?: MaskingConfig
}
export interface FieldsConfig {
  pid?: boolean
  time?: boolean
  msg?: boolean
  level?: boolean
}
export interface EnvConfig {
  output: OutputConfig
  fields?: FieldsConfig
}
export interface LoggerConfig {
  dev?: EnvConfig
  prod?: EnvConfig
}
